import { getProviders, getSession, useSession } from 'next-auth/react';

import Head from 'next/head';
import Feed from '../components/Feeds/Feed';
import Login from '../components/Login/Login';
import Sidebar from '../components/Sidebar/Sidebar';

export default function Home(props) {
  const { trendingResults, followResults, providers } = props;

  const { data: session } = useSession();

  if (!session) return <Login providers={providers} />;

  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-black flex min-h-screen max-w-[1500px] mx-auto'>
        <Sidebar />
        <Feed />
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch('https://jsonkeeper.com/b/NKEV').then(
    (res) => res.json()
  );
  const followResults = await fetch('https://jsonkeeper.com/b/WWMJ').then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}
