import Head from 'next/head';
import Feed from '../components/Feeds/Feed';
import Sidebar from '../components/Sidebar/Sidebar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-black flex min-h-screen max-w-[1500px] mx-auto'>
        <Sidebar />
        <Feed />
      </main>
    </div>
  );
}
