// NEXTJS/REACT
import { getProviders, getSession, useSession } from 'next-auth/react';
import Head from 'next/head';

// RECOIL
import { useRecoilState } from 'recoil';
import { modalState } from '../atoms/atomModal';

// COMPONENTS
import Feed from '../components/Feeds/Feed';
import Login from '../components/Login/Login';
import Modal from '../components/Modal/Modal';
import Sidebar from '../components/Sidebar/Sidebar';
import Widgets from '../components/SideWidgets/Widgets';

export default function Home(props) {
  const { trendingResults, followResults, providers } = props;

  const { data: session } = useSession();
  const [isOpen] = useRecoilState(modalState);

  // If there is no user return a Login component
  if (!session) return <Login providers={providers} />;

  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-black flex min-h-screen max-w-[1500px] mx-auto'>
        <Sidebar />
        <Feed />
        <Widgets
          trendingResults={trendingResults}
          followResults={followResults}
        />

        {isOpen && <Modal />}
      </main>
    </div>
  );
}

export async function getServerSideProps(context) {
  const trendingResults = await fetch('https://jsonkeeper.com/b/NKEV').then(
    (res) => res.json()
  );
  const followResults = await fetch('https://jsonkeeper.com/b/WWMJ').then(
    (res) => res.json()
  );
  const providers = await getProviders();
  const session = await getSession(context);

  return {
    props: {
      trendingResults,
      followResults,
      providers,
      session,
    },
  };
}
